/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExportHistoryRouteImport } from './routes/export-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatternsIndexRouteImport } from './routes/patterns/index'
import { Route as PatternsNewRouteImport } from './routes/patterns/new'
import { Route as PatternsSegmentRouteImport } from './routes/patterns/$segment'

const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportHistoryRoute = ExportHistoryRouteImport.update({
  id: '/export-history',
  path: '/export-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternsNewRoute = PatternsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternsSegmentRoute = PatternsSegmentRouteImport.update({
  id: '/$segment',
  path: '/$segment',
  getParentRoute: () => PatternsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export-history': typeof ExportHistoryRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/patterns/$segment': typeof PatternsSegmentRoute
  '/patterns/new': typeof PatternsNewRoute
  '/patterns/': typeof PatternsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export-history': typeof ExportHistoryRoute
  '/login': typeof LoginRoute
  '/patterns/$segment': typeof PatternsSegmentRoute
  '/patterns/new': typeof PatternsNewRoute
  '/patterns': typeof PatternsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export-history': typeof ExportHistoryRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/patterns/$segment': typeof PatternsSegmentRoute
  '/patterns/new': typeof PatternsNewRoute
  '/patterns/': typeof PatternsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export-history'
    | '/login'
    | '/patterns'
    | '/patterns/$segment'
    | '/patterns/new'
    | '/patterns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export-history'
    | '/login'
    | '/patterns/$segment'
    | '/patterns/new'
    | '/patterns'
  id:
    | '__root__'
    | '/'
    | '/export-history'
    | '/login'
    | '/patterns'
    | '/patterns/$segment'
    | '/patterns/new'
    | '/patterns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportHistoryRoute: typeof ExportHistoryRoute
  LoginRoute: typeof LoginRoute
  PatternsRoute: typeof PatternsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-history': {
      id: '/export-history'
      path: '/export-history'
      fullPath: '/export-history'
      preLoaderRoute: typeof ExportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/patterns/new': {
      id: '/patterns/new'
      path: '/new'
      fullPath: '/patterns/new'
      preLoaderRoute: typeof PatternsNewRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/patterns/$segment': {
      id: '/patterns/$segment'
      path: '/$segment'
      fullPath: '/patterns/$segment'
      preLoaderRoute: typeof PatternsSegmentRouteImport
      parentRoute: typeof PatternsRoute
    }
  }
}

interface PatternsRouteChildren {
  PatternsSegmentRoute: typeof PatternsSegmentRoute
  PatternsNewRoute: typeof PatternsNewRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

const PatternsRouteChildren: PatternsRouteChildren = {
  PatternsSegmentRoute: PatternsSegmentRoute,
  PatternsNewRoute: PatternsNewRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}

const PatternsRouteWithChildren = PatternsRoute._addFileChildren(
  PatternsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportHistoryRoute: ExportHistoryRoute,
  LoginRoute: LoginRoute,
  PatternsRoute: PatternsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
